name: 🐛 Bug report
description: Create a report to help us improve
labels: bug
assignees: jonnitto
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to complete this bug report!
  - type: markdown
    attributes:
      value: Please make sure to provide the information we ask for. This will allow us to help you better.
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of the current behaviour.
      placeholder: A bug happened!
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
      description: A description of what you expect to happen.
      placeholder: I expect to see X or Y
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please add a link to a repository with a minimal reproduction. Or describe accurately how we can reproduce/verify the bug.
      placeholder: |
        Example steps (replace with your own): \n
        1. Clone my repo at https://github.com/<myuser>/example \n
        2. pnpm build \n
        3. You should see the error come up
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of Carbon.Pipeline you are using.
      placeholder: ex. 0.10.1
    validations:
      required: true
  - type: textarea
    id: envinfo
    attributes:
      label: Environment
      description: |
        Please paste the output of running `npx envinfo --system`.
        This will be automatically formatted as a code block, so no need for backticks.
      placeholder: |
        System:
          OS:
          CPU:
          Memory:
          Shell:
      render: shell
    validations:
      required: true
  - type: textarea
    id: pnpminfo
    attributes:
      label: JS Package details
      description: |
        Please paste the output of running `pnpm ls esbuild postcss carbon-pipeline`.
        This will be automatically formatted as a code block, so no need for backticks.
      placeholder: |
        devDependencies:
        carbon-pipeline 0.1.1
        esbuild 0.14.25
        postcss 8.4.8
      render: shell
    validations:
      required: true
  - type: textarea
    id: composerminfo
    attributes:
      label: PHP Package details
      description: |
        Please paste the output of running `composer info carbon/pipeline`.
        This will be automatically formatted as a code block, so no need for backticks.
      placeholder: |
        name     : carbon/pipeline
        descrip. : Ultra-fast build stack for Neos CMS based on esbuild and PostCSS
        keywords : Neos, Preact, css, esbuild, javascript, postcss, react, sass, svelte, tailwind, typescript, vue
        versions : * 0.10.0
      render: shell
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might be relevant
    validations:
      required: false
