name: 'Basic test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  dependencies: 'tailwindcss@3 autoprefixer cssnano svelte svelte-preprocess esbuild-svelte vue esbuild-plugin-vue3 sass node-sass-tilde-importer'

jobs:
  pnpm:
    name: Test with pnpm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Copy files
        run: |
          mkdir -p Build/Carbon.Pipeline/
          cp -n Test/pipeline.yaml ./
          cp -n RootFiles/Global/{*,.*} ./ || true
          cp -n RootFiles/JavaScript/* ./ || true
          cp -n RootFiles/TailwindCSS3/{*,.*} ./ || true
          cp -R {Lib,defaults.yaml,*.mjs,*.cjs} Build/Carbon.Pipeline/
      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: latest
      - name: Setup node
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm add ${{ env.dependencies }}
      - name: Show config
        run: pnpm showConfig
      - name: Build CSS files
        run: pnpm build:css
      - name: Build JS files
        run: pnpm build:js

  yarn:
    name: Test with yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Copy files
        run: |
          mkdir -p Build/Carbon.Pipeline/
          cp -n Test/pipeline.yaml ./
          cp -n RootFiles/Global/{*,.*} ./ || true
          cp -n RootFiles/JavaScript/* ./ || true
          cp -n RootFiles/TailwindCSS3/{*,.*} ./ || true
          cp -R {Lib,defaults.yaml,*.mjs,*.cjs} Build/Carbon.Pipeline/
      - name: Setup node
        uses: actions/setup-node@v5.0.0
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: |
          yarn set version stable
          yarn install --no-immutable
          yarn add ${{ env.dependencies }}
      - name: Show config
        run: yarn showConfig
      - name: Build CSS files
        run: yarn build:css
      - name: Build JS files
        run: yarn build:js

  npm:
    name: Test with npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Copy files
        run: |
          mkdir -p Build/Carbon.Pipeline/
          cp -n Test/pipeline.yaml ./
          cp -n RootFiles/Global/{*,.*} ./ || true
          cp -n RootFiles/JavaScript/* ./ || true
          cp -n RootFiles/TailwindCSS3/{*,.*} ./ || true
          cp -R {Lib,defaults.yaml,*.mjs,*.cjs} Build/Carbon.Pipeline/
      - uses: actions/setup-node@v5.0.0
        with:
          node-version-file: .nvmrc
      - name: Install dependencies
        run: |
          npm install
          npm add ${{ env.dependencies }}
      - name: Show config
        run: npm run showConfig
      - name: Build CSS files
        run: npm run build:css
      - name: Build JS files
        run: npm run build:js
